---
# tasks file for vector-role
- name: Install RPMs from Vector site
  ansible.builtin.dnf:
    name: "https://packages.timber.io/vector/latest/{{ vector_version }}.x86_64.rpm"
    state: present
    disable_gpg_check: true
  with_items: "{{ vector_version }}"

- name: Create folder config vector
  file:
    path: /usr/conf
    state: directory

- name: Copy vector config
  become: true
  ansible.builtin.template:
    src: "templates/vector.toml"
    dest: "/usr/conf/vector.toml"
- name: Change file permissions vector.toml
  become: true
  ansible.builtin.file:
    path: "/usr/conf/vector.toml"
    state: file
    mode: "0765"
